### ISSUE TITLE
Сверстать нижний блок с артиклями из макета gridzilla_blog_item_page

### ISSUE THREAD

**Issue by Ermek-Kasymbekov** [vasview/html_group_9_teamwork_team_1#14]
# Что нужно сделать

Необходимо сверстать нижний блок с артиклями из макета gridzilla_blog_item_page
Можно позаимствовать из артикля в тех странице и изменить

# План работы.
 Сначала можно скопировать из артикля тех страницы, далее видоизменить
(в чате указана кликабельная часть элемента)
# Критерий готовности. 
 Открываем видим готовый блок
# Время работы
По плану: 1 часа.
По факту: 2 часа.

**Comment by vasview** [comment]
Коллеги, посмотри пожалуйста, правильно ли мы используем тэг а.

**Comment by vasview** [comment]
Нужно поиграться с адаптивностью
