### ISSUE TITLE
Подключить шрифты, закинуть картинки в папки

### ISSUE THREAD

**Issue by vasview** [vasview/html_group_9_teamwork_team_1#4]
# Что нужно сделать

Необходимо подключить нестандартные шрифты в проект, закинуть картинки из макета фотошопа.

# План работы.
По шрифтам:
  1. Определить используемые шрифты в проекте,
  2.   скачать их, 
  3.   поместить в папку fonts и
  4.   подключить их
По картинкам: 
 1. просмотреть файлы макеты
 2.  вырезать картинки из макета
 3.  поместить их в папки проекта, в зависимости от их контекста. 

# Критерий готовности. 
  В папках img и upload видим картинки для проекта. 
  В index.html видим линк на нестандартный шрифт.
# Время работы
По плану: 1 час.
По факту:

**Comment by vasview** [comment]
Ребята, у нас ошибки подключения шрифта. Смотрите в консоли.

**Comment by Ermek-Kasymbekov** [comment]
Да заметил, нужно бы разобраться в чем дело, благо время еще есть. Думаю стоит закончить весь скелет, далее копать ошибки
