### ISSUE TITLE
Собрать страницу gridzilla_contact

### ISSUE THREAD

**Issue by vasview** [vasview/html_group_9_teamwork_team_1#8]
# Что нужно сделать

Необходимо собрать страницу gridzilla_contact.

# План работы.
  Добавить шапку к странице. Добавить карту. Добавить подвал странице.
  Проверить адаптивность
# Критерий готовности. 
 Открываем страницу contact.html и видим полностью сверстанную страницу. 
# Время работы
По плану: 1 час.
По факту:  час. (5минут на шапку)

**Comment by nearia** [comment]
Собрал и вставил карту
